name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            client/package-lock.json
            api/package-lock.json
            
      - name: Install root dependencies
        run: |
          if [ -f package.json ]; then 
            npm cache clean --force
            npm install --legacy-peer-deps
          fi
          
      - name: Install client dependencies
        run: npm install --legacy-peer-deps
        working-directory: client
        
      - name: Install api dependencies
        run: |
          npm cache clean --force
          npm install --legacy-peer-deps
        working-directory: api
        
      - name: Build client
        run: |
          npm run build
          ls -la build/
        working-directory: client
        
      - name: Deploy to Azure Static Web Apps
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_FLOWER_0E2B98B03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"
          api_location: "api"
          output_location: "build"
          
      - name: Post Deployment Info
        run: echo "Deployment complete to Azure Static Web Apps"