name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use Node.js 18.x for better compatibility with Azure SDK
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x" # Changed to 18.x for stability
          cache: "npm"

      - name: Install root dev deps (SWA CLI)
        run: |
          if [ -f package.json ]; then npm ci; fi

      - name: Install client dependencies
        run: npm ci
        working-directory: client

      - name: Install api dependencies
        run: npm ci
        working-directory: api

      - name: Build client
        run: npm run build
        working-directory: client

      - name: Deploy to Azure Static Web Apps
        id: swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "client"
          api_location: "api"
          output_location: "build"

      - name: Post Deployment Info
        run: echo "Deployment complete"